backend/config.py
backend/db.py
backend/billing.py
backend/main.py
backend/requirements.txt
pipeline/Dockerfile
pipeline/handler.py
.github/workflows/pipeline-image.yml
.github/workflows/android-apk.yml
android/ScanForge/settings.gradle.kts
android/ScanForge/build.gradle.kts
android/ScanForge/gradle.properties
android/ScanForge/app/build.gradle.kts
android/ScanForge/app/src/main/AndroidManifest.xml
android/ScanForge/app/src/main/res/values/strings.xml
android/ScanForge/app/src/main/res/values/themes.xml
android/ScanForge/app/src/main/res/xml/file_paths.xml
android/ScanForge/app/src/main/java/com/scanforge/app/Api.kt
android/ScanForge/app/src/main/java/com/scanforge/app/JobStore.kt
android/ScanForge/app/src/main/java/com/scanforge/app/MainActivity.kt
android/ScanForge/app/src/main/java/com/scanforge/app/RingView.kt
android/ScanForge/app/src/main/java/com/scanforge/app/CaptureActivity.kt
android/ScanForge/app/src/main/java/com/scanforge/app/BillingManager.kt
android/ScanForge/app/src/main/java/com/scanforge/app/ResultActivity.kt
